In [62]:
import torchvision.datasets as dset
from torchvision import transforms
import torch
import numpy as np

mnist = dset.MNIST(root="/homes/li108/Dataset/Mnist", train=True,
                  transform=transforms.Compose([transforms.ToTensor()]))


train_loader = torch.utils.data.DataLoader(mnist, batch_size=100, shuffle=True)





In [65]:
for data, target in train_loader:
    pass

In [74]:
f = data.view([100, -1])

In [75]:
f.size()

torch.Size([100, 784])

In [56]:
b

array([3, 1, 2, 0, 9, 6, 8, 2, 6, 7, 1, 2, 2, 7, 9, 3, 7, 8, 6, 5, 7, 3, 7,
       9, 3, 9, 5, 3, 5, 3, 6, 5, 3, 2, 6, 1, 1, 1, 7, 7, 3, 1, 2, 5, 8, 0,
       3, 0, 7, 9, 5, 0, 4, 4, 1, 5, 1, 8, 2, 3, 7, 9, 3, 7, 3, 3, 1, 9, 8,
       0, 7, 0, 4, 0, 7, 4, 7, 0, 9, 7, 7, 7, 7, 0, 8, 7, 6, 8, 5, 9, 8, 7,
       6, 5, 0, 4, 6, 3, 2, 9])

In [59]:
c = np.zeros((100, 10))
c[np.arange(100), b] = 1

In [60]:
b

array([3, 1, 2, 0, 9, 6, 8, 2, 6, 7, 1, 2, 2, 7, 9, 3, 7, 8, 6, 5, 7, 3, 7,
       9, 3, 9, 5, 3, 5, 3, 6, 5, 3, 2, 6, 1, 1, 1, 7, 7, 3, 1, 2, 5, 8, 0,
       3, 0, 7, 9, 5, 0, 4, 4, 1, 5, 1, 8, 2, 3, 7, 9, 3, 7, 3, 3, 1, 9, 8,
       0, 7, 0, 4, 0, 7, 4, 7, 0, 9, 7, 7, 7, 7, 0, 8, 7, 6, 8, 5, 9, 8, 7,
       6, 5, 0, 4, 6, 3, 2, 9])

In [61]:
c

array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.

In [49]:
A = np.random.rand(4,5)
print(A)
print(A.mean())

[[ 0.41789438  0.6779124   0.27273909  0.35290299  0.26628685]
 [ 0.41678348  0.67065689  0.31530964  0.60555999  0.32066638]
 [ 0.56686131  0.28225678  0.59351182  0.46382687  0.43222917]
 [ 0.7551353   0.7484264   0.14270558  0.84547128  0.12451014]]
0.463582336882


In [51]:
A = [2,3,4]
mean(A)

NameError: name 'mean' is not defined